### ISSUE TITLE
OSMUD runtime configuration and arguments

### ISSUE THREAD

**Issue by kyeich** [osmud/osmud#11]
OSMUD will have configuration options that are needed to start the process. Implement reading this configuration from an "osmud.conf" file in simple key:value pairs. Also, all of these keys should be able to be provided to the executable as command line options (argc, argv). Command line options *must* override settings in "osmud.conf" definitions of the same option.

Options that would be set here are:
* Interfaces and their implementations
* Debug mode
* logging level
* Logging location
* run in deamon mode or stay in the foreground
* (I'm sure there are more)

Document how this works and how you add settings.

**Comment by danweller18** [comment]
We have arguments and no config file.  We don't need a conf file yet and can add one later. Run `osmud -h` to view all arguments.
