### ISSUE TITLE
Create firewall rule to block everything by default if we have a valid mudfile

### ISSUE THREAD

**Issue by danweller18** [osmud/osmud#39]
If a device has a mudfile, we are going to fail closed in osmud. This means that by default everything is blocked except when the mudfile has domains that say other wise (whitelist model)

**Comment by kyeich** [comment]
Should generate this rule in the /etc/config/firewall config file

config rule
	option name '<device-name>'
	option src 'lan'
	option src_ip '<ip addr>'
	option dest 'wan'
	option target 'REJECT'

**Comment by kyeich** [comment]
Execute this command to create a block-all rule:

./create_ip_fw_rule.sh -t REJECT -p all -s lan -i <ip-addr> -d wan -n "deny-all" -c <hostname> -f all -j any -b any -a any
