### ISSUE TITLE
DHCP server should handle the "MUDstring" dhcp header option passed to it

### ISSUE THREAD

**Issue by danweller18** [osmud/osmud#43]
DHCP clients will pass the dhcp server a MUDstring header that instructs the mud controller the location of the mud file server. 

for ipv4 it is dhcp header option 161
For ipv6 it is dhcp header option 112

modify dnsmasq to know how to handle this.

more info is found here: 
https://tools.ietf.org/html/draft-ietf-opsawg-mud#section-10

**Comment by kyeich** [comment]
Completed in osmud/dnsmasq fork and integrated with osmud via the detect_new_device.sh script.

**Comment by kyeich** [comment]
As part of this ticket, the dhcp-vendor information was also made available via the detect_new_device.sh script. It is implemented in osmud to read that value. Make sure a matching detect script is deployed along with osmud. This should not be an issue if installing via the opkg process.
