### ISSUE TITLE
weird non-shell at end of file

### ISSUE THREAD

**Issue by mcr** [osmud/osmud#91]
https://github.com/osmud/osmud/blob/e66f0339c9ba75681bf5e501d9185a313557502b/src/openwrt/create_ip_fw_rule.sh#L141

```
firewall.@rule[9]=rule
firewall.@rule[9].enabled='1'
firewall.@rule[9].target='ACCEPT'
firewall.@rule[9].src='lan'
firewall.@rule[9].dest='wan'
```

I'm not familiar with this shell notation :-).
The code ```firewall.@rule[9].dest_ip='52.72.66.3' ```
must be a mis-paste?

**Comment by danweller18** [comment]
Good catch- yeah that is not shell. Thats part of the OpenWRT uci syntax. Was probably left there on accident
